#Regresion Logística

Vamos a suponer que queremos predecir cuál es la probabilidad que tiene un estudiante de aprobar un examen en función de las horas que ha estudiado.

In [69]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# Preparar datos
x = np.array([0.5, 0.75, 1, 1.25, 1.5, 1.75, 1.75, 2, 2.25, 2.5, 2.75, 3, 3.25, 3.5, 4, 4.25, 4.5, 4.75, 5, 5.5]).reshape(-1,1)
y = np.array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1])
x_test = np.array([1, 2, 3, 4, 5, 6]).reshape(-1,1)

#Entrenamiento

In [80]:
#Crear una instancia de la Regresión Logística
#regresion_logistica = LogisticRegression()
regresion_logistica = LogisticRegression(solver='liblinear', random_state=0)

#Entrenar la regresión logística con los datos de entrenamiento
regresion_logistica.fit(x,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

#Predicción

In [81]:
# Usar el modelo entrenado para obtener las predicciones con datos nuevos
prediccion = regresion_logistica.predict(x_test)
print(prediccion)

[0 0 1 1 1 1]


In [82]:
# obtener las probabilidades de la predicción (opcional)
probabilidades_prediccion = regresion_logistica.predict_proba(x_test)
print("  Reprobar     Aprobar")
print(probabilidades_prediccion)

# Como seguramente estamos más interesados en la probabilidad de aprobar,
# podemos centrarnos en la segunda columna
print("-----Probabilidades de aprobar -----")
print(probabilidades_prediccion[:,1])


  Reprobar     Aprobar
[[0.6801015  0.3198985 ]
 [0.53568295 0.46431705]
 [0.38502138 0.61497862]
 [0.25359079 0.74640921]
 [0.15566862 0.84433138]
 [0.09095092 0.90904908]]
-----Probabilidades de aprobar -----
[0.3198985  0.46431705 0.61497862 0.74640921 0.84433138 0.90904908]


#Evaluacion

In [83]:
cm = confusion_matrix(y, regresion_logistica.predict(x))
cm

array([[7, 3],
       [1, 9]])

In [84]:
print(classification_report(y, regresion_logistica.predict(x)))

              precision    recall  f1-score   support

           0       0.88      0.70      0.78        10
           1       0.75      0.90      0.82        10

    accuracy                           0.80        20
   macro avg       0.81      0.80      0.80        20
weighted avg       0.81      0.80      0.80        20

